#+TITLE: Emacs literate configuration
#+AUTHOR: Javier Castilla
#+EMAIL: jcastp@pm.me
#+LANGUAGE: en
#+STARTUP: overview

* Summary
This is the literate config for my emacs use cases.

I will try to document and compartmentalize the sections, so it's easier to follow up, but it won't always be possible, as some functions overlap, and I'm usually a messy person when speaking of testing.
* Lexical binding added
#+begin_src emacs-lisp
  ;; -*- lexical-binding: t; -*-
#+end_src
* git related config
** magit
Git control version.
https://cestlaz-nikola.github.io/posts/using-emacs-47-magit/

#+begin_src emacs-lisp
  (use-package transient
    :ensure t)

  (use-package magit
    :ensure t
    :after transient
    :bind
    (:map global-map
  	("C-x g" . magit-status)))
  #+end_src
  
** diff-hl
To show where the file has been modified.
https://github.com/dgutov/diff-hl
#+begin_src emacs-lisp
  (use-package diff-hl
    :ensure t
    :config
    (global-diff-hl-mode)
    (add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
    (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh))
#+end_src
* General config
** Unmap the C-z key
Unmap the C-z key, so no way to minimize or suspend emacs accidentally.
#+begin_src emacs-lisp
  (global-unset-key (kbd "C-z"))
#+end_src

** Garbage collection
Fine tune the garbage collection.
#+begin_src emacs-lisp
   (use-package gcmh
    :ensure t
    :diminish gcmh-mode
    :custom
    (gcmh-mode 1)
    (gcmh-idle-delay 10)
    (gcmh-high-cons-threshold (* 100 1024 1024))
    (gc-cons-percentage 0.8))
#+end_src

** Alternative and better C-g function
https://emacsredux.com/blog/2025/06/01/let-s-make-keyboard-quit-smarter/

#+begin_src emacs-lisp
  (defun er-keyboard-quit-dwim ()
    "Do-What-I-Mean behaviour for a general `keyboard-quit'.

  The generic `keyboard-quit' does not do the expected thing when
  the minibuffer is open.  Whereas we want it to close the
  minibuffer, even without explicitly focusing it.

  The DWIM behaviour of this command is as follows:

  - When the region is active, disable it.
  - When a minibuffer is open, but not focused, close the minibuffer.
  - When the Completions buffer is selected, close it.
  - In every other case use the regular `keyboard-quit'."
    (interactive)
    (cond
     ((region-active-p)
      (keyboard-quit))
     ((derived-mode-p 'completion-list-mode)
      (delete-completion-window))
     ((> (minibuffer-depth) 0)
      (abort-recursive-edit))
     (t
      (keyboard-quit))))

  (global-set-key [remap keyboard-quit] #'er-keyboard-quit-dwim)
#+end_src

** Start with a maximized frame
#+begin_src emacs-lisp
  (add-to-list 'default-frame-alist '(fullscreen . maximized))
#+end_src

** Minibuffer completion
https://www.masteringemacs.org/article/understanding-minibuffer-completion
https://git.sr.ht/~ashton314/emacs-bedrock/tree/main/item/init.el
#+begin_src emacs-lisp
  (setq enable-recursive-minibuffers t)  ; Use the minibuffer whilst in the minibuffer
  (setq completion-cycle-threshold 1)    ; TAB cycles candidates
  (setq completions-detailed t)          ; Show annotations
  (setq tab-always-indent 'complete)     ; When I hit TAB, try to complete, otherwise, indent
#+end_src

** fringe bars
We put some fringe space in the frames.
#+begin_src emacs-lisp
  (fringe-mode 0)
#+end_src

** Changes all yes/no questions to y/n type
The questions are answered with a y or n, instead of yes or no.
#+begin_src emacs-lisp
  (setq use-short-answers t)  
#+end_src

** Sentences end with just one space
#+begin_src emacs-lisp
  (setq sentence-end-double-space nil)
#+end_src

** Ask before closing emacs
To avoid closing everything because I slip my finger ...
#+begin_src emacs-lisp
  (setq confirm-kill-emacs 'y-or-n-p)
#+end_src

** Network security set to high
Enforcing the network security.
https://www.gnu.org/software/emacs/manual/html_node/emacs/Network-Security.html
#+begin_src emacs-lisp
  (setq network-security-level 'high)
#+end_src

** No lock files, but backups
No lock files created:
#+begin_src emacs-lisp
  (setq create-lockfiles nil)
#+end_src

But backups are good to have:
#+begin_src emacs-lisp
  ;; backup in one place. flat, no tree structure
  ;; TODO change this to the variables for directories as it does not work as expected
  (setq backup-directory-alist '(("" . "~/Nextcloud/config/.emacs.d/backups")))
  ;; What if the file is linked? We copy the file
  (setq backup-by-copying t)
  ;; Version control
  (setq delete-old-versions t
        kept-new-versions 6
        kept-old-versions 2
        version-control t)
#+end_src

** utf-8 everywhere
UTF-8 everywhere.
#+begin_src emacs-lisp
  ;; make sure that UTF-8 is used everywhere.
  (set-terminal-coding-system  'utf-8)
  (set-keyboard-coding-system  'utf-8)
  (set-language-environment    'utf-8)
  (set-selection-coding-system 'utf-8)
  (setq-default buffer-file-coding-system 'utf-8)
  (setq locale-coding-system   'utf-8)
  (prefer-coding-system        'utf-8)
  (set-input-method nil)
#+end_src

** Movement
Some keys redefined to better adjust to the whole emacs key environment.
#+begin_src emacs-lisp
  (global-set-key (kbd "M-p") 'backward-paragraph)
  (global-set-key (kbd "M-n") 'forward-paragraph)
#+end_src

** OS interaction
These settings relate to how emacs interacts with your operating system.
#+begin_src emacs-lisp
  (setq
   ;; makes killing/yanking interact with the system clipboard
   select-enable-clipboard t

   ;; This is explained here:
   ;; https://superuser.com/questions/90257/what-is-the-difference-between-the-x-clipboards
   ;; https://unix.stackexchange.com/questions/139191/whats-the-difference-between-primary-selection-and-clipboard-buffer
   select-enable-primary t

   ;; Save clipboard strings into kill ring before replacing them.
   ;; When one selects something in another program to paste it into Emacs,
   ;; but kills something in Emacs before actually pasting it,
   ;; this selection is gone unless this variable is non-nil
   save-interprogram-paste-before-kill t

   ;; Shows all options when running apropos. For more info,
   ;; https://www.gnu.org/software/emacs/manual/html_node/emacs/Apropos.html
   apropos-do-all t

   ;; Mouse yank commands yank at point instead of at click.
   mouse-yank-at-point t)
#+end_src

** auto revert mode
When a file is changed in disk, the buffer reloads to reflect that change.
#+begin_src emacs-lisp
  (global-auto-revert-mode 1)
#+end_src

Change dired buffers when the directory is changed:
#+begin_src emacs-lisp
  ;; auto refresh dired when file changes
  (add-hook 'dired-mode-hook 'auto-revert-mode)
#+end_src

** eww configuration
Set the userAgent for eww.
#+begin_src emacs-lisp
  (setq url-user-agent "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0")
#+end_src

** dired config
All the configurations needed for dired.
 #+begin_src emacs-lisp
   (use-package dired
     :ensure nil
     :commands (dired dired-jump)
     :hook
     (;; (dired-mode . dired-hide-details-mode)
      (dired-mode . hl-line-mode))
     :config
     (setq dired-recursive-copies 'always)
     (setq dired-recursive-deletes 'always)
     (setq delete-by-moving-to-trash t)
     (setq dired-dwim-target t)
     ;; directories first in the listings
     (setq dired-listing-switches "-aBhl  --group-directories-first"))
 #+end_src

*** dired subtree
Show subdirectory contents with tab.

From Prot's article - https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/
#+begin_src emacs-lisp
  (use-package dired-subtree
    :ensure t
    :after dired
    :bind
    ( :map dired-mode-map
      ("<tab>" . dired-subtree-toggle)
      ("TAB" . dired-subtree-toggle)
      ("<backtab>" . dired-subtree-remove)
      ("S-TAB" . dired-subtree-remove))
    :config
    (setq dired-subtree-use-backgrounds nil))
#+end_src

** set firefox or librewolf as the default browser
Setting firefox or librewolf as the default browser for opening http/s links.
#+begin_src emacs-lisp
  (setq librewolf_path "/usr/bin/librewolf")
  ;; check if librewolf is installed
  (if (file-exists-p librewolf_path)
       (progn
         (setq browse-url-firefox-program "librewolf")
         (setq browse-url-browser-function 'browse-url-firefox))
    ;; if no librewolf installed, we fall back to firefox
     (progn
       (setq browse-url-firefox-program "firefox")
       (setq browse-url-browser-function 'browse-url-firefox)))
#+end_src

** Battery management
I want to know how much battery if using a laptop.
#+begin_src emacs-lisp
  ;; Use this only on laptops...
  (unless (string-match-p "^Power N/A" (battery))
    ;; it's nice to know how much power you have
    (display-battery-mode 1))
#+end_src

** electric pair mode
To automatically close parenthesis and other punctuation signs.
Specially defined for spanish question and exclamation marks.
#+begin_src emacs-lisp
  (electric-pair-mode 1)
  ;; make electric-pair-mode work on more sets of punctuation signs.
  (setq electric-pair-pairs
        '(
          (?\¡ . ?\!)
          (?\¿ . ?\?)))

  (setq electric-pair-inhibit-predicate
        `(lambda (c)
           (if (char-equal c ?<) t (,electric-pair-inhibit-predicate c))))
#+end_src

** vundo - undo with visual cues
#+begin_src emacs-lisp
  (use-package vundo
    :ensure t
    :config
    (global-set-key (kbd "C-z") #'vundo))
#+end_src

** vlf related config
Very large files loading.
#+begin_src emacs-lisp
  ;; very large files support
  (use-package vlf
    :ensure t
    :config
    (require 'vlf-setup))
#+end_src

** openwith
Open particular files with external applications.
#+begin_src emacs-lisp
  (use-package openwith
    :ensure t
    :config
    (when (require 'openwith nil 'noerror)
      (setq openwith-associations
            (list
             ;; videos
             (list (openwith-make-extension-regexp
                    '("mpg" "mpeg" "mp3" "mp4"
                      "avi" "wmv" "wav" "mov" "flv"
                      "ogm" "ogg" "mkv"))
                   "vlc"
                   '(file))
             ;; office documents
             (list (openwith-make-extension-regexp
                    '("doc" "docx" "xls" "xlsx" "ppt" "pptx"
                      "odt" "ods" "odg" "odp" "fodg"
                      "fods" "fodt"))
                   "libreoffice"
                   '(file))
             ;; help documents
             '("\\.lyx" "lyx" (file))
             '("\\.chm" "kchmviewer" (file))
             ;; pdf files
             ;; (list (openwith-make-extension-regexp
             ;;        '("pdf" "ps" "ps.gz" "dvi"))
             ;;       "okular"
             ;;       '(file))
             ))
      (openwith-mode 1)))
#+end_src

** free keys
Shows the free keybinding. Useful to assign new keybindings to some new functions.
#+begin_src emacs-lisp
  (use-package free-keys
    :ensure t
    :defer t
    :commands (free-keys))
#+end_src

** Which-key
After pressing a key combo, it shows the key bindings associated.
#+begin_src emacs-lisp
  ;; only use use-package for versions under 30, as version >30 have which-key as a default
  (if (version<= "30" emacs-version)
      (which-key-mode)
    (progn (
  	  (use-package which-key
              :ensure t
              :config
              (which-key-mode)
              ))))

   (use-package which-key-posframe
     :config
     (which-key-posframe-mode))
#+end_src

** expand region
https://github.com/magnars/expand-region.el

Select relevant regions incrementally.
#+begin_src emacs-lisp
  (use-package expand-region
    :ensure t
    :config
    (global-set-key (kbd "C-ñ") 'er/expand-region))
#+end_src

** project.el configuration
#+begin_src emacs-lisp
  (setq project-list-file (expand-file-name "projects" my-data-dir))
#+end_src

** Reload my configuration
Reload this configuration file.
#+begin_src emacs-lisp
  (defun my/reload-config()
    "Reloads my orgmode configuration."
    (interactive)
    (load (concat user-emacs-directory "early-init.el"))
    (load (concat user-emacs-directory "init.el")))
  (global-set-key (kbd "C-c r r" ) 'my/reload-config)
#+end_src

** Spelling
https://www.gnu.org/software/emacs/manual/html_node/emacs/Spelling.html

*** Flyspell mode
Automatic spelling in the buffer.
This conflicts with orgmode archive =C-c $=.

#+begin_src emacs-lisp
  (use-package flyspell
    :custom
    ;; Configure =hunspell= as the orthographic corrector, as it is the more modern option.
    ;; aspell is good enough, but it has stopped being developed.
    (ispell-program-name "hunspell")
    (ispell-dictionary "en_US,es_ES")
    (ispell-personal-dictionary (expand-file-name "dict" my-data-dir))
    (ispell-silently-savep t)
    :config
    ;; Also adding the "spanish" path, because somehow it doesn't work. It finds "castellano", but not "spanish".
    (add-to-list 'ispell-hunspell-dict-paths-alist '("spanish" "/usr/share/hunspell/es_ES.aff"))
    (ispell-set-spellchecker-params)
    (ispell-hunspell-add-multi-dic "en_US,es_ES")
    (global-font-lock-mode t)
    :hook
    (text-mode . flyspell-mode))
#+end_src

** Delete after selecting a text area
This allows to delete a selected text area immediately, just as other text editors.

From Prot's article - https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/
#+begin_src emacs-lisp
   (use-package delsel
     :ensure nil ; no need to install it as it is built-in
     :hook (after-init . delete-selection-mode))
#+end_src

** helpful package
#+begin_src emacs-lisp
  (use-package helpful
    :ensure t
    :bind
    ("C-h f" . helpful-callable)
    ("C-h v" . helpful-variable)
    ("C-h k" . helpful-key)
    ("C-h x" . helpful-command))
#+end_src

** Abbreviation mode
Defines a set of abbreviations that permits complete words with just some characters.
#+begin_src emacs-lisp
  ;;where do we read the abbrevs from
  (setq abbrev-file-name (expand-file-name "abbrev_defs" my-data-dir))
  (add-hook 'text-mode-hook 'abbrev-mode)
  (add-hook 'prog-mode-hook 'abbrev-mode)
  ;; save abbrevs when files are saved
  (setq save-abbrevs 'silently)
#+end_src

* vertico, prescient, consult, marginalia, embark
** vertico
Vertical auto completion in the minibuffer
https://github.com/minad/vertico
#+begin_src emacs-lisp
  (use-package vertico
    :ensure t
    :init
    (load "vertico-multiform.el")
    (vertico-mode))
#+end_src

*** vertico posframe
#+begin_src emacs-lisp
  (use-package vertico-posframe
    :ensure t
    :after vertico
    :init
    (vertico-posframe-mode 1)
    :config
    (setq vertico-posframe-width 120)
    (setq vertico-posframe-height 12)
    (setq vertico-multiform-commands
  	'((consult-line
             posframe
             (vertico-posframe-poshandler . posframe-poshandler-frame-top-center)
             (vertico-posframe-border-width . 10)
             ;; NOTE: This is useful when emacs is used in both in X and
             ;; terminal, for posframe do not work well in terminal, so
             ;; vertico-buffer-mode will be used as fallback at the
             ;; moment.
             (vertico-posframe-fallback-mode . vertico-buffer-mode))
            (t posframe)))
    (vertico-multiform-mode 1))
#+end_src

** prescient
For better auto completion suggestions:
https://github.com/raxod502/prescient.el
#+begin_src emacs-lisp
  (use-package prescient
    :ensure t
    :config
    (prescient-persist-mode 1)
    (setq prescient-save-file (expand-file-name "prescient-save" my-data-dir))
    )

  ;; To use prescient with vertico
  (use-package vertico-prescient
    :ensure t
    :config
    (vertico-prescient-mode 1))
#+end_src

** consult
Completion from a list of candidates, and has enhanced commands.
https://github.com/minad/consult
#+begin_src emacs-lisp
  (use-package consult
    :ensure t
    :demand t
    :bind (
           ;; misc commands
           ;;("C-x b" . consult-buffer) ;; defined in perspective section
           ("C-x r b" . consult-bookmark)
           ("M-y" . consult-yank-from-kill-ring)
  	 ;;("C-c d t" . consult-theme)
           ;; Go commands
           ("M-g M-g" . consult-goto-line)
  	 ;;("C-c d o" . consult-outline)
  	 ("M-i" . consult-imenu)
           ("M-g i" . consult-imenu-multi)
           ;;("M-g o" . consult-outline)
           ("M-g h" . consult-org-heading)
           ("M-g a" . consult-org-agenda)
           ("M-g m" . consult-mark)
           ;; Search commands
           ("C-s" . consult-line)
           ("M-s f" . consult-find)
           ("M-s L" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . consult-ripgrep)))
#+end_src

** marginalia
Add side anotations to the completion buffer
https://github.com/minad/marginalia/
#+begin_src emacs-lisp
  (use-package marginalia
    :ensure t
    :init
      (marginalia-mode))
#+end_src

** embark
This package provides a sort of right-click contextual menu for Emacs, accessed through the embark-act command (which you should bind to a convenient key), offering you relevant actions to use on a target determined by the context:
https://github.com/oantolin/embark/
#+begin_src emacs-lisp
  (use-package embark
    :ensure t
    :bind
    (("C-." . embark-act)         ;; pick some comfortable binding
     ;;("C-;" . embark-dwim)        ;; good alternative: M-.
     ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'

    :init
    ;; Optionally replace the key help with a completing-read interface
    (setq prefix-help-command #'embark-prefix-help-command)

    :config
    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none)))))

  ;; Consult users will also want the embark-consult package.
  (use-package embark-consult
    :ensure t
    :after (embark consult)
    :demand t ; only necessary if you have the hook below
    ;; if you want to have consult previews as you move around an
    ;; auto-updating embark collect buffer
    :hook
    (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

** orderless
To have completion based on parts of words, and sepparated by spaces.
https://github.com/oantolin/orderless
#+begin_src emacs-lisp
  (use-package orderless
    :ensure t
    :init
    ;; Configure a custom style dispatcher (see the Consult wiki)
    ;; (setq orderless-style-dispatchers '(+orderless-dispatch)
    ;;       orderless-component-separator #'orderless-escapable-split-on-space)
    (setq completion-styles '(orderless basic)
          completion-category-defaults nil
          completion-category-overrides '((file (styles partial-completion)))))
#+end_src

** corfu completion
https://github.com/minad/corfu
Vertico completes the minibuffer, while corfu completes in buffer.
#+begin_src emacs-lisp
  (use-package corfu
    :ensure t
    ;; Optional customizations
    :custom
    (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    (corfu-auto t)                 ;; Enable auto completion
    (corfu-auto-delay 0.8)         ;; delay for the autocompletion
    (corfu-separator ?\s)          ;; Orderless field separator
    ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
    (corfu-preview-current nil)   
    (corfu-preselect 'prompt)      ;; Preselect the prompt
    ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches
    ;; (corfu-scroll-margin 5)        ;; Use scroll margin

    ;; This is recommended since Dabbrev can be used globally (M-/).
    ;; See also `corfu-exclude-modes'.
    :init
    (global-corfu-mode))
#+end_src

** TODO cape - completions at point
https://github.com/minad/cape
#+begin_src emacs-lisp
  (use-package cape
    :ensure t
    :bind ("C-c p" . cape-prefix-map) ;; Alternative keys: M-p, M-+, ...
    ;; Alternatively bind Cape commands individually.
    ;; :bind (("C-c p d" . cape-dabbrev)
    ;;        ("C-c p h" . cape-history)
    ;;        ("C-c p f" . cape-file)
    ;;        ...)
    :init
    ;; Add to the global default value of `completion-at-point-functions' which is
    ;; used by `completion-at-point'.  The order of the functions matters, the
    ;; first function returning a result wins.  Note that the list of buffer-local
    ;; completion functions takes precedence over the global list.
    (add-hook 'completion-at-point-functions #'cape-dabbrev)
    (add-hook 'completion-at-point-functions #'cape-file)
    (add-hook 'completion-at-point-functions #'cape-elisp-block))
#+end_src

* Navigation
** Uniquify
When several buffers visit identically-named files, Emacs must give the buffers distinct names. The usual method for making buffer names unique adds ‘<2>’, ‘<3>’, etc. to the end of the buffer names (all but one of them).

The forward naming method includes part of the file's directory name at the beginning of the buffer name
https://www.gnu.org/software/emacs/manual/html_node/emacs/Uniquify.html
#+begin_src emacs-lisp
  ;; (require 'uniquify)
  (setq uniquify-buffer-name-style 'forward)
#+end_src

** Keyboard chords
Shortcuts to commands using just quick key combinations.
#+begin_src emacs-lisp
    (use-package key-chord
      :ensure t
      :demand t
      :init
      (key-chord-mode 1)
      :config
      ;; Max time delay between two key presses to be considered a key chord
      (setq key-chord-two-keys-delay 0.15)
      ;; Max time delay between two presses of the same key to be considered a key chord.
      ;; Should normally be a little longer than `key-chord-two-keys-delay'.
      (setq key-chord-one-key-delay 0.25) ; default 0.2
      
      ;; eshell related commands
      (key-chord-define-global "ññ" 'eshell)
      (key-chord-define-global "ñl" 'my/eshell-new) ;; create a new eshell buffer

      ;; Window related commands
      ;; (key-chord-define-global "kk" 'other-window)
      (key-chord-define-global "hh" 'ace-window)

      ;; move related commands
      (key-chord-define-global "jj" 'avy-goto-char-2)
      (key-chord-define-global "jk" 'avy-goto-char-timer)
      (key-chord-define-global "jl" 'avy-goto-line))
      
      ;; (key-chord-define-global "zz" 'undo-tree-visualize)
      ;; (key-chord-define-global "ww" 'hydra-move/body)
      ;; (key-chord-define-global "yy" 'hydra-buffer-mgmt/body)
#+end_src

** Imenu-list
Imenu shows the outline of your file as a browsable sidebar in another window.
#+begin_src emacs-lisp
  (use-package imenu-list
    :ensure t
    :config
    ;; set the width to % of the screen
    (setq imenu-list-size 0.20)
    ;; rescan all the buffers
    (setq imenu-auto-rescan t)
    ;; put the imenu in the position we want
    (setq imenu-list-position 'left)
    ;; Establish the depth of the entries shown
    (setq org-imenu-depth 5)
    ;; Auto-resize after update to nil
    (setq imenu-list-auto-resize nil)
    ;; map the keys
    (global-unset-key (kbd "M-i"))
    (global-set-key (kbd "M-g I") #'imenu-list-smart-toggle)
    ;; Once you open imenu, focus on it
    (setq imenu-list-focus-after-activation t))
#+end_src

** ace-window
To better manage more buffers in screen, as seen here: https://github.com/abo-abo/ace-window

Used in the hydra snippets.
#+begin_src emacs-lisp
  (use-package ace-window
    :ensure t
    :config
    (setq aw-scope 'frame)
    (setq aw-keys '(?a ?s ?d ?f ?g ?h ?j ?k ?l))
    (global-set-key (kbd "M-o") 'ace-window)
    ;; make the characters bigger, so it is easy to see
    (custom-set-faces
     '(aw-leading-char-face
       ((t (:inherit ace-jump-face-foreground :height 5.0))))))
#+end_src

** avy
A better way to jump through text.
https://github.com/abo-abo/avy
#+begin_src emacs-lisp
  (use-package avy
    :ensure t)
#+end_src

** perspective.el
https://github.com/nex3/perspective-el
#+begin_src emacs-lisp
  (use-package perspective
    :ensure t
    :custom
    (persp-mode-prefix-key (kbd "C-c w"))  ; pick your own prefix key here
    :bind
    ("C-c w w" . persp-switch)
    ("C-c w b" . persp-ibuffer)         ; or use a nicer switcher, see below
    ;; Redefining the buffer search to align with persp philosophy.
    ("C-x b" . persp-switch-to-buffer*)
    ("C-x C-b" . persp-switch-to-buffer)
    :init
    (persp-mode)
    :config
    ;; sort the persps by the creation time
    (setq persp-sort 'created))
#+end_src

*** TODO automatic load some perspectives
This function allows to load my defined perspectives and sessions.

#+begin_src emacs-lisp
  (with-eval-after-load 'perspective
    ;; where I define my own perspective saved files
    (setq my-persp-save-dir (expand-file-name  "perspectives/" my-data-dir))

    ;; a function to load a perspective saved file from a given directory
    (defun my/load-perspective ()
      "Given a directory with perspective saved files, the user chooses one, and it automatically
    loads it."
      ;; 
      (interactive)
      (let ((file (read-file-name "Select a file: " my-persp-save-dir)))
        (persp-state-load file)
        ;; show a message
        (message "You chose: %s" file)))

    (define-key persp-mode-map (kbd "C-c w l") 'my/load-perspective))
#+end_src

But I want to automatically load some perspectives when I'm at home:
#+begin_src emacs-lisp
  (defvar my-persp-load nil
    "Define if we want to load the personal persp.")

  (if (and my-homeenvironment-p my-persp-load)
      (progn
        (with-eval-after-load 'org
  	(defvar my-persp-files '(
      				 "config-persp"
      				 "tareas-persp"
  				 "escritura-persp"
      				 ))

  	(dolist (my-file my-persp-files)
  	  (persp-state-load (f-join my-persp-save-dir my-file))))))
#+end_src

* UI improvements
** Number of columns and rows
Don't put the number of lines and columns in the mini line.

#+begin_src emacs-lisp
  (setq line-number-mode nil)
  (setq column-number-mode nil)
#+end_src

** No blinking cursor
Cursor doesn't blink:
#+begin_src emacs-lisp
  (blink-cursor-mode 0)
#+end_src

** Highlight the current line
I don't need my line to be highlighted.
#+begin_src emacs-lisp
  ;; Don't highlight the current line
  (global-hl-line-mode 0)
#+end_src

** Font size increase/decrease
Increase or decrease the font size
#+begin_src emacs-lisp
  (global-set-key (kbd "M-+") 'text-scale-increase)
  (global-set-key (kbd "M--") 'text-scale-decrease)
#+end_src

** full path in the title bar
Put the complete path on the title bar, along the filename.
#+begin_src emacs-lisp
  (setq-default frame-title-format "%b - (%f)")
#+end_src

** Time and date
Put time and date on the status line
#+begin_src emacs-lisp
  (setq display-time-day-and-date t
        display-time-24hr-format t)
  (display-time)
#+end_src

** Highlight matching parenthesis
You can see the matching parenthesis
#+begin_src emacs-lisp
  (show-paren-mode 1)
#+end_src

** Tabs are 4 spaces
#+begin_src emacs-lisp
  (setq tab-width 4) ; or any other preferred value
  ;; (defvaralias 'c-basic-offset 'tab-width)
  (defvaralias 'cperl-indent-level 'tab-width)
#+end_src

** Fontify the header
Fontify the whole line for headings (with a background color). Works well with Leuven theme:

#+begin_src emacs-lisp
  (setq org-fontify-whole-heading-line nil)
#+end_src

Different sizes for the different org headings.
#+begin_src emacs-lisp
   (custom-theme-set-faces
    'user
    `(org-level-4 ((t (:height 1.0))))
    `(org-level-3 ((t (:height 1.1))))
    `(org-level-2 ((t (:height 1.2))))
    `(org-level-1 ((t (:height 1.3))))
    `(org-document-title ((t (:height 1.6 :underline nil)))))
#+end_src

** Open indirect buffer
Open a branch into a different frame, but the same buffer:

TODO: Search how to check if there is another right frame open or not.
#+begin_src emacs-lisp
(defun my/org-tree-open-in-right-frame ()
  "Open the current Org subtree in an indirect buffer in the right window.
If there is only one window, create a right-side window first.
Then, always move focus to that right window."
  (interactive)
  (let ((right-win (window-right (selected-window))))
    ;; If there's no window to the right, create one
    (unless right-win
      (setq right-win (split-window-right)))
    ;; Show the subtree in an indirect buffer
    (org-tree-to-indirect-buffer)
    ;; Move to the right window
    (select-window right-win)))
 
  (global-set-key (kbd "C-c 8" ) 'my/org-tree-open-in-right-frame)
#+end_src

** No bell
No audible bell, but visual one:
#+begin_src emacs-lisp
  (setq ring-bell-function 'ignore)
  (setq visible-bell t)
#+end_src

** Line numbers
This determines the style of line numbers in effect. If set to `nil', line numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
  ;; Calculate width based on total lines in buffer at start
  (setq display-line-numbers-width-start t)
  (setq display-line-numbers-offset 0)
  (setq display-line-numbers-type t)
  (setq display-line-numbers-grow-only t)
  (global-display-line-numbers-mode 1)
#+end_src

** Highlight indent guides
Highlight the indent guides with a pipe character, so it's easier to see where we need to align the code.
https://github.com/DarthFennec/highlight-indent-guides
#+begin_src emacs-lisp
  (use-package highlight-indent-guides
    :ensure t
    :config
    (setq highlight-indent-guides-method 'character)
    (setq highlight-indent-guides-character ?\|)
    (add-hook 'prog-mode-hook 'highlight-indent-guides-mode))
#+end_src

** Long lines get wrapped
Long lines get wrapped when they reach the edge. We activate it for all the buffers.
#+begin_src emacs-lisp
  (global-visual-line-mode 1) ; 1 for on, 0 for off.
#+end_src

** Fill column mode
We want to use the visual fill column mode to limit the width of the lines, even if they don't reach the right edge.

When reaching the established width defined, the line will wrap, even before getting into the right border of the application.
#+begin_src emacs-lisp
  ;; visual fill column mode
  (use-package visual-fill-column
    :ensure t
    :config
    ;; This sets the value to all the buffers, as initially it is a per-buffer variable
    (setq-default visual-fill-column-width 110)
    ;; set the text in the center of the window
    (setq-default visual-fill-column-center-text t))
#+end_src

** All the icons
Get all the fancy icons.
#+begin_src emacs-lisp
  ;; From Prot's article - https://protesilaos.com/codelog/2024-11-28-basic-emacs-configuration/
  (use-package nerd-icons
    :ensure t)

  (use-package nerd-icons-completion
    :ensure t
    :after marginalia
    :config
    (add-hook 'marginalia-mode-hook #'nerd-icons-completion-marginalia-setup))

  (use-package nerd-icons-corfu
    :ensure t
    :after corfu
    :config
    (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

  (use-package nerd-icons-dired
    :ensure t
    :hook
    (dired-mode . nerd-icons-dired-mode))
#+end_src

** doom modeline
Doom modeline.
#+begin_src emacs-lisp
  (use-package doom-modeline
    :ensure t
    ;;:hook (after-init . doom-modeline-mode)
    :init
    (doom-modeline-mode 1)
    :config
    (setq doom-modeline-height 25)
    (setq doom-modeline-icon t)
    (setq doom-modeline-major-mode-icon t)
    (setq doom-modeline-major-mode-color-icon t)
    (setq doom-modeline-buffer-state-icon t)
    (setq doom-modeline-buffer-modification-icon t)
    ;; Do we need to show the minor modes?
    (setq doom-modeline-minor-modes nil)
    ;; word count of the buffer disabled, as it slows operations when word count grows
    ;; (setq doom-modeline-enable-word-count t)
    ;; Major modes in which to display word count continuously.
    ;; Also applies to any derived modes. Respects `doom-modeline-enable-word-count'.
    ;; If it brings the sluggish issue, disable `doom-modeline-enable-word-count' or
    ;; remove the modes from `doom-modeline-continuous-word-count-modes'.
    ;; (setq doom-modeline-continuous-word-count-modes '(markdown-mode gfm-mode org-mode))
    (setq doom-modeline-env-version t)
    (setq doom-modeline-buffer-encoding nil)
    (setq doom-modeline-indent-info nil)
    (setq doom-modeline-buffer-file-name-style 'auto)
    ;; github status in the modeline
    (setq doom-modeline-github nil)
    ;; Whether display the `lsp' state. Non-nil to display in the mode-line.
    (setq doom-modeline-lsp t)
    ;; Whether display the time. It respects `display-time-mode'.
    (setq doom-modeline-time t))
#+end_src

** Dimmer
It darkens the buffers I'm not using.
#+begin_src emacs-lisp
  (use-package dimmer
    :ensure t
    :config
    (dimmer-configure-which-key)
    (dimmer-mode t)
    (dimmer-configure-magit)
    ;;(dimmer-configure-org)

    ;; configure the dimmer
    (setq dimmer-adjustment-mode :background)
    (setq dimmer-fraction 0.1))
#+end_src

** Highlighting the line when changing windows
#+begin_src emacs-lisp
  (use-package pulsar
    :after consult
    :ensure t
    :hook
    (consult-after-jump . pulsar-recenter-top)
    (consult-after-jump . pulsar-reveal-entry)
    :config
    (setq pulsar-pulse t)
    (setq pulsar-delay 0.1)
    (setq pulsar-iterations 10)
    (setq pulsar-face 'pulsar-red)
    (setq pulsar-highlight-face 'pulsar-yellow)
    ;; integration with the `consult' package:
    ;;(add-hook 'consult-after-jump-hook #'pulsar-recenter-top)
    ;;(add-hook 'consult-after-jump-hook #'pulsar-reveal-entry)
    ;; enable everywhere
    (pulsar-global-mode 1)
    :bind
    ("C-x l" . pulsar-highlight-line))
#+end_src

** spacious padding
This package provides a global minor mode to increase the spacing/padding of Emacs windows and frames. The idea is to make editing and reading feel more comfortable.

https://github.com/protesilaos/spacious-padding
#+begin_src emacs-lisp
  (use-package spacious-padding
    :ensure t
    :config
    (setq spacious-padding-widths
  	'( :internal-border-width 15
             :header-line-width 4
             :mode-line-width 6
             :tab-width 4
             :right-divider-width 30
             :scroll-bar-width 8))
    (spacious-padding-mode 1))
#+end_src

** Center a buffer in screen
Sometimes I have just a single window and this is a problem for me in a big screen. This code just centers the text in the middle.
Useful for reading books or long texts.

#+begin_src emacs-lisp
  (defcustom my/centered-content-width 100
    "Width of the centered content area in characters."
    :type 'integer
    :group 'editing-basics)

  (defun my/centered-content-width-value ()
    "Prompt the user for a value and set `my/centered-content-width` to it."
    (interactive)
    (setq my/centered-content-width (string-to-number (read-from-minibuffer "Value for centered width: "))))

  (defvar my/centered-mode nil)

  (define-minor-mode my/centered-mode
    "Minor mode to center buffer content using margins and visual line mode."
    :init-value nil
    :global nil
    :lighter " [Centered]"
    :group 'editing-basics
    (if my/centered-mode
        (progn
          (visual-line-mode 1)
          (add-hook 'window-configuration-change-hook 
                    #'my/centered--update-margins nil t)
          (my/centered--update-margins))
      (progn
        (visual-line-mode 1)
        (remove-hook 'window-configuration-change-hook 
                     #'my/centered--update-margins t)
        (set-window-margins nil 0 0))))

  (defun my/centered--update-margins ()
    "Calculate and apply margins to center 100-character content."
    (let* ((width (frame-width))
           (margin (max 0 (/ (- width my/centered-content-width) 2))))
      (set-window-margins nil margin margin)))
#+end_src

** emacs-rotate
To rotate the layout of the windows.
https://github.com/daichirata/emacs-rotate

#+begin_src emacs-lisp
  (use-package rotate
    :ensure t
    :defer t)
#+end_src

* Fonts and themes
** Themes
*** leuven themes
#+begin_src emacs-lisp
  (use-package leuven-theme
    :ensure t)
#+end_src

*** Protesilaos modus themes
Protesilaos very good themes. These themes are already included in the standard emacs, so we can get rid of the use-package definition, and retain only the config.
#+begin_src emacs-lisp
  (use-package modus-themes
    :ensure t
    :config
    ;; Add all your customizations prior to loading the themes
    (setq
     modus-themes-completions nil
     modus-themes-bold-constructs t
     modus-themes-italic-constructs t
     modus-themes-success-deuteranopia t
     modus-themes-mixed-fonts t
     modus-themes-intense-markup t
     modus-themes-tabs-accented t
     modus-themes-org-blocks '(tinted-background)
     modus-themes-variable-pitch-ui nil
     modus-themes-variable-pitch-headings nil

     modus-themes-fringes nil ; {nil,'subtle,'intense}

     ;; fonts for headings
     modus-themes-headings
     '((1 . (background overline rainbow 1.10))
       (2 . (overline rainbow 1.05))
       (3 . (rainbow 1.1))
       (4 . (rainbow no-bold 1.0))
       (t . (monochrome no-bold 1.0)))
     ;; scales up the headings
     modus-themes-scale-headings t))
#+end_src

*** Protesilaos ef themes
#+begin_src emacs-lisp
  (use-package ef-themes
    :ensure t)
#+end_src

*** poet theme
https://github.com/kunalb/poet
#+begin_src emacs-lisp
  (use-package poet-theme
    :ensure t
    :defer t)
#+end_src

*** doric themes
#+begin_src emacs-lisp
  (use-package doric-themes
    :ensure t)
#+end_src

** Font setup
Look at this https://idiocy.org/emacs-fonts-and-fontsets.html
*** fonts as variables
Establish the fonts with variables, so we don't need to change them on evey place (like in fontaine modes)

#+begin_src emacs-lisp
  ;; variable pitch variables
  (defvar my-variable-font "Aporetic Sans")
  (defvar my-variable-font-height 140)

  ;; fixed pitch variables
  (defvar my-fixed-font "Aporetic Sans Mono")
  (defvar my-fixed-font-height 110)

  ;; My default font variables
  (defvar my-default-font "Aporetic Sans Mono")
  (defvar my-default-font-height 120)
#+end_src

*** font definition
#+begin_src emacs-lisp
  ;;(set-face-attribute 'default nil :font "Aporetic Sans Mono")
  (set-face-attribute 'default nil :font my-default-font)
#+end_src

Obtained from: https://zzamboni.org/post/beautifying-org-mode-in-emacs/
Font attributes to be used, different for prose mode and code mode.

Fonts we will be using for both modes:
#+begin_src emacs-lisp
  (custom-theme-set-faces
   'user
   `(variable-pitch
     ;; variable font config
     ((t (:family ,my-variable-font
  		:height ,my-variable-font-height
           	:weight Regular))))

   ;; fixed font config
   `(fixed-pitch
     ((t (:family ,my-fixed-font
  		:height ,my-fixed-font-height
  		:weight Medium))))

   ;; default font config
   `(default
     ((t (:family ,my-default-font
  		:height ,my-default-font-height
  		:weight Light)))))

#+end_src

Assign the variable font to prose mode:
#+begin_src emacs-lisp
  (add-hook 'text-mode-hook 'variable-pitch-mode)
  (add-hook 'org-mode-hook 'variable-pitch-mode)
#+end_src

Use fixed font for code blocks and other non prose blocks, and configure all other aspects on how to show them on screen:
#+begin_src emacs-lisp
  (custom-theme-set-faces
   'user
   '(org-block                 ((t (:inherit fixed-pitch))))
   '(org-block-begin-line      ((t (:foreground "dim grey" :weight bold :height 1.1 :inherit fixed-pitch))))
   '(org-document-info         ((t (:foreground "dark orange"))))
   '(org-document-info-keyword ((t (:inherit (shadow fixed-pitch)))))
   '(org-link                  ((t (:foreground "royal blue" :underline t))))
   '(org-meta-line             ((t (:inherit (font-lock-comment-face fixed-pitch)))))
   '(org-property-value        ((t (:inherit fixed-pitch))) t)
   '(org-special-keyword       ((t (:inherit (font-lock-comment-face fixed-pitch)))))
   '(org-tag                   ((t (:inherit (shadow fixed-pitch) :weight bold :height 0.9))))
   '(org-verbatim              ((t (:inherit (shadow fixed-pitch)))))
   '(org-indent                ((t (:inherit (org-hide fixed-pitch)))))
   '(org-table                 ((t (:inherit (org-hide fixed-pitch)))))
   ;; check if this works
   '(org-comment               ((t (:inherit (org-hide fixed-pitch) :height 0.8)))))
#+end_src

** fontaine
Allows to set different fonts dinamically.
https://protesilaos.com/emacs/fontaine

#+begin_src emacs-lisp
    (use-package fontaine
      :ensure t)
#+end_src

* Orgmode config
All orgmode configs
** some org configs for better behavior and usage
#+begin_src emacs-lisp
  (setq
   ;; tag alignment
   ;; this value allows for modern themes and column fill to work well together.
   org-auto-align-tags t
   org-tags-column -90
   ;; org fold - edit in an invisible region
   org-fold-catch-invisible-edits 'show-and-error
   ;; C-a and C-e will move the cursor just the heading. No todo keyworks, no tags
   org-special-ctrl-a/e t
   ;; insert new heading after the current subtree
   org-insert-heading-respect-content t)
#+end_src

** org templates modification
I want some modifications on the templates provided by org mode.

#+begin_src emacs-lisp
  (setq org-structure-template-alist
        '(("a" . "export ascii")
  	("c" . "comment")
  	("C" . "center")
  	("d" . "comment summary")
  	("e" . "example")
  	("E" . "export")
  	("h" . "export html")
  	("l" . "export latex")
  	("n" . "comment note")
  	("q" . "quote")
  	("s" . "src")
  	("S" . "src emacs-lisp")
  	("v" . "verse")))
#+end_src

** org-id configuration
To create and use internal valid and unique links in org-mode, we will use the =org-id= features.

#+begin_src emacs-lisp
  ;; org-id are globally unique UUIDs
  (setq org-id-method 'uuid)
  ;; It will use the CUSTOM_ID, if it exists
  ;;or will create a new one in the form or UUID, as seen above
  (setq org-id-link-to-org-use-id 'create-if-interactive-and-no-custom-id)
  ;; file to store the local =org-id= locations
  ;; This way is synced to all my computers
  (setq org-id-locations-file (expand-file-name "org-id-locations" my-data-dir))
#+end_src

** org-toc
Table of Contents for orgmode documents. I don't use it that much, but can be useful.

https://github.com/snosov1/toc-org

#+begin_src emacs-lisp
  (use-package toc-org
    :ensure t
    :config
    (add-hook 'org-mode-hook 'toc-org-mode))
#+end_src

** org-indent-mode on all the buffers
I need to have the orgmode indented to see clearly where I am, so I enable it on every orgmode buffer.
#+begin_src emacs-lisp
  (add-hook 'org-mode-hook
            (lambda ()
              (org-indent-mode t))
            t)
#+end_src

** Leave an empty line before headings
#+begin_src emacs-lisp
  (setq org-blank-before-new-entry '(
                                     (heading . t)
                                     (plain-list-item . nil)))
#+end_src

** Custom keybindings for org mode
Global custom keys to do things in org mode.
#+begin_src emacs-lisp
  (global-set-key "\C-cl" 'org-store-link)
  (global-set-key "\C-cc" 'org-capture)
  (global-set-key "\C-ca" 'org-agenda)
  (global-set-key "\C-cb" 'org-switchb)
#+end_src

** Completion notes in to the Logbook
Change notes are stored in the node's drawer, so we can fold it conveniently.
#+begin_src emacs-lisp
  (setq org-log-into-drawer t)
#+end_src

** Custom notes and timestamp
Put a note or a timestamp when something changes. For example:
- When the tasks is marked as DONE
- When the schedule or deadline date is changed
#+begin_src emacs-lisp
  ;; Adds a timestamp to the state
  ;;(setq org-log-done 'time)
  ;; Adds a custom note to the state
  ;;(setq org-log-done 'note)
  (setq org-log-done nil)

  ;; When the deadline or the schedule date is moved.
  ;; to keep track of how many times I have moved a task to the future.
  ;;(setq org-log-redeadline (quote time))
  (setq org-log-redeadline nil)
  ;;(setq org-log-reschedule (quote time))
  (setq org-log-reschedule nil)
#+end_src

** TODO Custom faces for org-todo-keywords
#+begin_src emacs-lisp :tangle yes
  ;; Define theme-adaptive faces for org-todo keywords
  (defface my/org-todo-active
    '((((class color) (background light))
       :foreground "#b60000" :weight bold)
      (((class color) (background dark))
       :foreground "#ff8f88" :weight bold))
    "Face for active TODO keywords.")

  (defface my/org-todo-next
    '((((class color) (background light))
       :foreground "#005f5f" :background "#c4ede0" :weight bold)
      (((class color) (background dark))
       :foreground "#6ae4b9" :background "#00382f" :weight bold))
    "Face for NEXT keyword - ready to work on.")

  (defface my/org-todo-waiting
    '((((class color) (background light))
       :foreground "#813e00" :background "#fff0c0" :weight bold)
      (((class color) (background dark))
       :foreground "#fec43f" :background "#4a3000" :weight bold))
    "Face for WAITING/HOLD keywords.")

  (defface my/org-todo-cancelled
    '((((class color) (background light))
       :foreground "#70627f" :strike-through t)
      (((class color) (background dark))
       :foreground "#9f94a5" :strike-through t))
    "Face for CANCELLED keyword.")

  (defface my/org-todo-done
    '((((class color) (background light))
       :foreground "#006800" :weight bold)
      (((class color) (background dark))
       :foreground "#44bc44" :weight bold))
    "Face for DONE keyword.")

  ;; Apply faces to keywords
  (setq org-todo-keyword-faces
        '(("TODO"      . my/org-todo-active)
          ("NEXT"      . my/org-todo-next)
          ("WAITING"   . my/org-todo-waiting)
          ("HOLD"      . my/org-todo-waiting)
          ("CANCELLED" . my/org-todo-cancelled)
          ("DONE"      . my/org-todo-done)))
#+end_src

** org-clock
Remap the org-clock-in to a better key binding.
#+begin_src emacs-lisp
  (defun my/org-set-clock ()
    "One-off function for `org-mode' task clocking.

  Behaviour:
   ,* When there is no running clock, start the clock for the item at point.
   ,* When there is already a running clock and `point' is at the item which is being clocked stop the corresponding clock.
   ,* When there is already a running clock but `point' is not at the item which is being clocked, stop the clock and restart it for item at `point'."
    (interactive)
    (let ((interrupting (and (not org-clock-resolving-clocks-due-to-idleness)
                             (org-clocking-p))))
      (if interrupting
          (if (save-excursion
                (org-back-to-heading t)
                (and (equal (marker-buffer org-clock-hd-marker)
                            (current-buffer))
                     (= (marker-position org-clock-hd-marker)
                        (point))
                     (equal org-clock-current-task (nth 4 (org-heading-components)))))
              (org-clock-out)
            (org-clock-in))
        (org-clock-in))))

  ;; keybindings
  (global-set-key (kbd "C-c C-x C-i") 'org-clock-in)
  (global-set-key (kbd "C-c C-x C-o") 'org-clock-out)
  (global-set-key (kbd "C-c C-x i") 'my/org-set-clock)
#+end_src

** Capture to this buffer
Inspired by https://github.com/ballantony/emacs-writing/blob/main/DoomEmacsWriting.org

Used to capture notes in this file. Useful to maintain notes and snippets separated by projects.
#+begin_src emacs-lisp
  (defun my/capture-to-this-buffer ()
    "Capture a note to the current buffer’s file, under the headline \"Notes\")."
    (interactive)
    ;; Make sure we are in an Org buffer.
    (unless (derived-mode-p 'org-mode)
      (user-error "Can’t capture to a non‑Org buffer"))

      ;; Choose the destination that actually exists.
      (let ((target (buffer-file-name)))
        ;; Build a temporary capture template that points at TARGET.
        (let ((org-capture-templates
               `(("t" "Todo"
                  entry
                  (file+headline ,target "Notes")
                  "** TODO %?"))))
          ;; Run the capture UI.
          (org-capture))))

  (global-set-key (kbd "C-c C") 'my/capture-to-this-buffer)
#+end_src

** org-babel
Don't ask for confirmation during org babel execution.
#+begin_src emacs-lisp
  (setq org-confirm-babel-evaluate nil)
#+end_src

** Orgmode visuals config
This section manages the visual look of org mode.

*** Initial org-mode look
https://lucidmanager.org/productivity/ricing-org-mode/

#+begin_src emacs-lisp
  ;; Improve org mode looks
  (setq org-pretty-entities t
        org-startup-with-inline-images t
        org-image-actual-width '(800)
        org-hide-emphasis-markers t)

  ;; Line spacing, in pixels
  (setq-default line-spacing 0)

  ;; Change the ellipsis
  (setq org-ellipsis "…")

  ;; Add frame borders and window dividers
  (modify-all-frames-parameters
   '((right-divider-width . 10)
     (internal-border-width . 10)))
  (dolist (face '(window-divider
                  window-divider-first-pixel
                  window-divider-last-pixel))
    (face-spec-reset-face face)
    (set-face-foreground face (face-attribute 'default :background)))
  (set-face-background 'fringe (face-attribute 'default :background))
#+end_src

*** Org with spaces instead of the asterisks
Some people find it noisy and distracting that the Org headlines start with a potentially large number of stars, and that text below the headlines is not indented. While this is no problem when writing a book-like document where the outline headings are really section headings, in a more list-oriented outline, indented structure is a lot cleaner.

#+begin_src emacs-lisp
  (setq org-startup-indented t)
#+end_src

*** org-appear
Show the invisible markers, only when the cursor is on them.
/Test/ this with *these* _examples_.

#+begin_src emacs-lisp
  (use-package org-appear
    :ensure t
    :hook (org-mode . org-appear-mode))
#+end_src

*** org-modern
https://github.com/minad/org-modern

#+begin_src emacs-lisp
  (use-package org-modern
    :ensure t
    :hook
    (org-mode . org-modern-mode)
    :custom
    (org-modern-hide-stars 'leading)
    (org-modern-table nil)
    ;; (org-modern-keyword nil)
    (org-modern-timestamp nil)
    ;; (org-modern-priority t)
    (org-modern-checkbox nil)
    (org-modern-tag t)
    ;; (org-modern-block-name nil)
    (org-modern-footnote nil)
    (org-modern-internal-target nil)
    (org-modern-radio-target nil)
    ;; (org-modern-statistics nil)
    ;; (org-modern-progress nil)
    ;; The progress bar for task pending/completed is too wide for me
    (org-modern-progress 8))
#+end_src

** Orgmode extra packages
*** TODO org-ql
Query language for org files
https://github.com/alphapapa/org-ql

#+begin_src emacs-lisp
  (use-package org-ql
    :ensure t
    :bind
    ("C-c q f" . org-ql-find-in-agenda)
    ("C-c q s" . org-ql-search)
    ("C-c q v" . org-ql-view))
  ;; adding this to load some org-ql libraries on startup
  (require 'org-ql-search)
#+end_src

*** graphs via dot
https://www.graphviz.org/pdf/dotguide.pdf

** Pandoc exporter
#+begin_src emacs-lisp
  (use-package ox-pandoc
    :ensure t)
#+end_src

** Create an org scratch buffer
https://emacs.stackexchange.com/questions/16492/is-it-possible-to-create-an-org-mode-scratch-buffer

When you want to write something fast using org mode, but you don't want to create a new file.

#+begin_src emacs-lisp
  (defun my/scratch-org-buffer ()
    "Create a new scratch buffer -- \*hello-world\*"
    (interactive)
    (let ((n 0)
          bufname buffer)
      (catch 'done
        (while t
          (setq bufname (concat "*org-scratch"
  			      (if (= n 0) "" (int-to-string n))
  			      "*"))
          (setq n (1+ n))
          (when (not (get-buffer bufname))
            (setq buffer (get-buffer-create bufname))
            (with-current-buffer buffer
              (org-mode)
  	    (insert "# org-scratch buffer\n"))
            ;; When called non-interactively, the `t` targets the other window (if it exists).
            (throw 'done (select-window (display-buffer buffer t))))))))
#+end_src

* org-roam config
** org-roam general configuration

This is a fix for a Debian installation that doesn't allow connecting directly
to the sqlite backend.
#+begin_src emacs-lisp
  (defun which-linux-distribution ()
    "from lsb_release"
    (interactive)
    (when (eq system-type 'gnu/linux)
      (shell-command-to-string "lsb_release -sd")))

  (when (string-prefix-p "Debian" (which-linux-distribution))
    (use-package sqlite3
      :ensure t))
#+end_src

#+begin_src emacs-lisp
  ;; main org-roam config
  (use-package org-roam
    :ensure t
    :init
    (setq org-roam-v2-ack t)
    (setq org-roam-directory (file-truename "~/Nextcloud/org-roam"))
    (setq org-roam-db-location (file-truename "~/Nextcloud/org-roam/org-roam.db"))
    :bind (
           ("C-c n l" . org-roam-buffer-toggle)
           ("C-c n f" . org-roam-node-find)
           ("C-c n i" . org-roam-node-insert)
           ("C-c n c" . org-roam-capture)
           ("C-c n t" . org-roam-tag-add)
           ("C-c n r" . org-roam-ref-add)
           ("C-c n u" . org-roam-ui-open)

           :map org-roam-dailies-map
           ("Y" . org-roam-dailies-capture-yesterday)
           ("U" . org-roam-dailies-capture-today)
           ("I" . org-roam-dailies-capture-tomorrow)
           )
    :bind-keymap
    ("C-c n d" . org-roam-dailies-map)
    :config
    (setq org-roam-completion-everywhere t)
    (require 'org-roam-dailies)
    (require 'org-roam-export)
    (org-roam-db-autosync-mode 1))
#+end_src

Open fleeting notes with a keybinding:
#+begin_src emacs-lisp
  (defun my/org-roam-fleeting-notes ()
    "Open my org-roam file with my fleeting notes"
    (interactive)
    (find-file "~/Nextcloud/org-roam/personal/fleeting_notes.org"))
  (global-set-key (kbd "C-c n F") 'my/org-roam-fleeting-notes)
#+end_src

Base org-roam capture templates. Personal-only templates (book notes, writing)
are added via =add-to-list= in =emacs-config-personal.org=.
#+begin_src emacs-lisp
  (setq org-roam-capture-templates
        '(
          ;; personal note — lands in personal/
          ("p" "personal note" plain
           "* TODO ${title}\n%?"
           :if-new (file+head "personal/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+title: ${title}\n")
           :unnarrowed t)

          ;; work concept note — lands in work/
          ("k" "work concept" plain
           "* ${title}\n%?"
           :if-new (file+head "work/%<%Y%m%d%H%M%S>-${slug}.org"
                              "#+title: ${title}\n#+filetags: work\n")
           :unnarrowed t)))
#+end_src

Org-roam window configuration:
#+begin_src emacs-lisp
  (add-to-list 'display-buffer-alist
               '("\\*org-roam\\*"
                 (display-buffer-in-side-window)
                 (side . right)
                 (slot . 0)
                 (window-width . 0.33)
                 (window-parameters . ((no-other-window . t)
                                       (no-delete-other-windows . t)))))
#+end_src

Search by title and tags:
#+begin_src emacs-lisp
  (setq org-roam-node-display-template
        (concat "${title:*} "
                (propertize "${tags:20}" 'face 'org-tag)))
#+end_src

** org-roam UI
#+begin_src emacs-lisp
  (use-package websocket
    :ensure t)
  (use-package simple-httpd
    :ensure t)
  (use-package org-roam-ui
    :ensure t
    :hook (org-roam . org-roam-ui-mode))

  (setq org-roam-dailies-directory "daily/")

  (setq org-roam-dailies-capture-templates
        '(("d" "default" entry
           "* %?"
           :if-new (file+head "%<%Y-%m-%d>.org"
                              "#+title: %<%Y-%m-%d>\n#+filetags: daily\n"))))
#+end_src

** Restrict agenda to org-roam
Functions to isolate the org-roam TODOs from the general agenda.
Extracted from https://d12frosted.io/posts/2021-01-16-task-management-with-roam-vol5.html
#+begin_src emacs-lisp
  (if (not (require 'org-roam nil t))
      (message "org-roam not found")

    (setq my/roamtag "roamtag")

    (defun vulpea-buffer-prop-set (name value)
      "Set a file property called NAME to VALUE in buffer file.
      If the property is already set, replace its value."
      (setq name (downcase name))
      (org-with-point-at 1
        (let ((case-fold-search t))
          (if (re-search-forward (concat "^#\\+" name ":\\(.*\\)")
                                 (point-max) t)
              (replace-match (concat "#+" name ": " value) 'fixedcase)
            (while (and (not (eobp))
                        (looking-at "^[#:]"))
              (if (save-excursion (end-of-line) (eobp))
                  (progn
                    (end-of-line)
                    (insert "\n"))
                (forward-line)
                (beginning-of-line)))
            (insert "#+" name ": " value "\n")))))

    (defun vulpea-buffer-prop-set-list (name values &optional separators)
      "Set a file property called NAME to VALUES in current buffer.
      VALUES are quoted and combined into single string using
      `combine-and-quote-strings'.
      If SEPARATORS is non-nil, it should be a regular expression
      matching text that separates, but is not part of, the substrings.
      If nil it defaults to `split-string-default-separators', normally
      \"[ \f\t\n\r\v]+\", and OMIT-NULLS is forced to t.
      If the property is already set, replace its value."
      (vulpea-buffer-prop-set
       name (combine-and-quote-strings values separators)))

    (defun vulpea-buffer-tags-set (&rest tags)
      "Set TAGS in current buffer.
        If filetags value is already set, replace it."
      (vulpea-buffer-prop-set "filetags" (string-join tags " ")))

    (defun vulpea-buffer-prop-get (name)
      "Get a buffer property called NAME as a string."
      (org-with-point-at 1
        (when (re-search-forward (concat "^#\\+" name ": \\(.*\\)")
                                 (point-max) t)
          (buffer-substring-no-properties
           (match-beginning 1)
           (match-end 1)))))

    (defun vulpea-buffer-prop-get-list (name &optional separators)
      "Get a buffer property NAME as a list using SEPARATORS.
          If SEPARATORS is non-nil, it should be a regular expression
          matching text that separates, but is not part of, the substrings.
          If nil it defaults to `split-string-default-separators', normally
          \"[ \f\t\n\r\v]+\", and OMIT-NULLS is forced to t."
      (let ((value (vulpea-buffer-prop-get name)))
        (when (and value (not (string-empty-p value)))
          (split-string-and-unquote value separators))))

    (defun vulpea-buffer-tags-get ()
      "Return filetags value in current buffer."
      (vulpea-buffer-prop-get-list "filetags" " "))

    (defun vulpea-buffer-tags-add (tag)
      "Add a TAG to filetags in current buffer."
      (let* ((tags (vulpea-buffer-tags-get))
             (tags (append tags (list tag))))
        (apply #'vulpea-buffer-tags-set tags)))

    (defun vulpea-project-p ()
      "Return non-nil if current buffer has any todo entry.

              TODO entries marked as done are ignored, meaning the this
              function returns nil if current buffer contains only completed
              tasks."
      (seq-find
       (lambda (type)
         (eq type 'todo))
       (org-element-map
           (org-element-parse-buffer 'headline)
           'headline
         (lambda (h)
           (org-element-property :todo-type h)))))

    (defvar vulpea--updating-tag nil
      "Re-entry guard for `vulpea-project-update-tag'.")

    (defun vulpea-project-update-tag ()
      "Update PROJECT tag in the current buffer."
      (unless vulpea--updating-tag
        (let ((vulpea--updating-tag t))
          (when (and (not (active-minibuffer-window))
                     (vulpea-buffer-p))
            (save-excursion
              (goto-char (point-min))
              (let* ((tags (vulpea-buffer-tags-get))
                     (original-tags tags))
                (if (vulpea-project-p)
                    (setq tags (cons "roamtag" tags))
                  (setq tags (remove "roamtag" tags)))
                (setq tags (seq-uniq tags))
                (when (or (seq-difference tags original-tags)
                          (seq-difference original-tags tags))
                  (apply #'vulpea-buffer-tags-set tags))))))))

    (defun vulpea-buffer-p ()
      "Return non-nil if the currently visited buffer is a note."
      (and buffer-file-name
           (string-prefix-p
            (expand-file-name (file-name-as-directory org-roam-directory))
            (file-name-directory buffer-file-name))))

    (defun vulpea-project-files ()
      "Return a list of note files containing 'roamtag' tag."
      (seq-uniq
       (seq-map
        #'car
        (org-roam-db-query
         [:select [nodes:file]
                  :from tags
                  :left-join nodes
                  :on (= tags:node-id nodes:id)
                  :where (like tag (quote "%\"roamtag\"%"))]))))

    (add-hook 'find-file-hook #'vulpea-project-update-tag)
    (add-hook 'before-save-hook #'vulpea-project-update-tag))
#+end_src

Just show the TODOs from org-roam, not from the general agenda:
#+begin_src emacs-lisp
  (defun my/agenda-restrict-to-roam ()
    "Restrict agenda to current project"
    (interactive)
    (let ((org-agenda-files (list org-roam-directory)))
      (org-agenda)))
  (global-set-key (kbd "C-c n a") 'my/agenda-restrict-to-roam)
#+end_src

** org-roam random node opening
Opens a random org-roam node:
#+begin_src emacs-lisp
  (defun my/random-roam-node ()
    "Opens a random org-roam node."
    (interactive)
    (setq todo-nodes
          (org-roam-db-query
           [:select [nodes:file]
                    :from tags
                    :left-join nodes
                    :on (= tags:node-id nodes:id)
                    ]))
    (find-file (car (nth (random (length todo-nodes)) todo-nodes))))

  (global-set-key (kbd "C-c n R") 'my/random-roam-node)
#+end_src

Opens a random org-roam node with the roamtag tag (maps to a TODO entry):
#+begin_src emacs-lisp
  (defun my/random-roam-todo-node ()
    "Opens a random org-roam node with the roamtag tag."
    (interactive)
    (setq todo-nodes
          (org-roam-db-query
           [:select [nodes:file]
                    :from tags
                    :left-join nodes
                    :on (= tags:node-id nodes:id)
                    :where (like tag (quote "%\"roamtag\"%"))]))
    (find-file (car (nth (random (length todo-nodes)) todo-nodes))))

  (global-set-key (kbd "C-c n T") 'my/random-roam-todo-node)
#+end_src

* Programming
** General

*** flycheck config
Check language syntax on the fly.

#+begin_src emacs-lisp
  (use-package flycheck
    :ensure t
    :demand t
    :init
    (global-flycheck-mode t))

  (with-eval-after-load 'flycheck
    ;; change the key bindings, as ther conflict with org mode
    (define-key flycheck-mode-map flycheck-keymap-prefix nil)
    (setq flycheck-keymap-prefix (kbd "C-c g"))
    (define-key flycheck-mode-map flycheck-keymap-prefix
                flycheck-command-map))
#+end_src

** tree-sitter config
Tree-Sitter is included in newer versions of emacs.x
We just need to load the languages.

#+begin_src emacs-lisp
  (use-package tree-sitter
    :ensure t
    :defer t
    :config
    (add-hook 'prog-mode #'tree-sitter-mode) ; only used in prog-mode
    (add-hook 'tree-sitter-after-on-hook #'tree-sitter-hl-mode)) ; syntax highlighting
    
  (use-package tree-sitter-langs
    :ensure t
    :after tree-sitter)
#+end_src

ts-fold to fold code in a convenient way.

#+begin_src emacs-lisp
  ;; to fold code blocks based on tree-sitter
  (use-package ts-fold
    :vc (:url "https://github.com/emacs-tree-sitter/ts-fold"
  	    :branch "main")
    :bind
    ("C-<return>" . ts-fold-toggle)
    ("C-M-<return>". ts-fold-close-all)
    :hook
    ((prog-mode-hook . ts-fold-mode)
     (ts-fold-mode . ts-fold-indicators-mode))
    :config
    (setq ts-fold-line-count-show t))
#+end_src
** eglot configuration
Configuring eglot to work with vanilla python and its tree-sitter enabled mode:
#+begin_src emacs-lisp 
  (use-package eglot
    :ensure nil
    :config
    ;;(add-to-list 'eglot-server-programs '(python-mode . ("pylsp")))
    (add-to-list 'eglot-server-programs '(python-ts-mode . ("pylsp")))

    (setq-default eglot-workspace-configuration
  		'((:pylsp . (:configurationSources ["flake8"] :plugins (:pycodestyle (:enabled nil) :mccabe (:enabled nil) :flake8 (:enabled t))))))

    :hook
    ;;((python-mode . eglot-ensure))
    ((python-ts-mode . eglot-ensure)))
    #+end_src

** Shell scripts

#+begin_src emacs-lisp
  (setq-default sh-basic-offset 2)
  (setq-default sh-indentation 2)
#+end_src

** Python
All python related configuration

*** Python v3
Use python3 to run code.

#+begin_src emacs-lisp
  (setq python-shell-interpreter "python3")
#+end_src

*** Eglot inspect mode on python-ts-mode
#+begin_src emacs-lisp
  (add-hook 'python-ts-mode-hook 'treesit-inspect-mode)
#+end_src

* Miscellanea
** gnuplot
GNUplot for emacs, to use in plotting graphics from tables.

#+begin_src emacs-lisp
  (use-package gnuplot
    :ensure t
    :defer t)
#+end_src

** hydra
Use of hydra for some purposes.

*** hydra for resizing windows
This serves to resize the windows

#+begin_src emacs-lisp
  (use-package hydra
    :ensure t
    :config
    (global-unset-key (kbd "C-c k"))
    (global-set-key
     (kbd "C-c k")
     (defhydra hydra-resize
       (:body-pre (next-line))
       "
  ^Resize^
  ^^^^^^-------------------------------------------------------
  _f_: shrink horizontally         _s_: swap windows
  _b_: enlarge horizontally        _r_: rotate layout
  _p_: shrink vertical
  _n_: enlarge vertical
  "

       ;; ("<left>" shrink-window-horizontally)
       ;; ("<right>" enlarge-window-horizontally)
       ;; ("<up>" enlarge-window)
       ;; ("<down>" shrink-window)
       ("f" shrink-window-horizontally)
       ("b" enlarge-window-horizontally)
       ("p" enlarge-window)
       ("n" shrink-window)
       ("s" ace-swap-window)
       ("r" rotate-layout)

       ("q" nil "quit"))))
#+end_src

** pdf-tools
#+begin_src emacs-lisp
  (use-package pdf-tools
    :ensure t
    :config
    ;; don't ask when installing pdf-tools
    (pdf-tools-install t))

  (use-package saveplace-pdf-view
    :ensure t
    :config
    (save-place-mode 1))
#+end_src

** eshell improvements

*** eshell-z
Replicates the z function from zsh.
#+begin_src emacs-lisp
  (use-package eshell-z
    :ensure t
    :after eshell
    :config
    (add-hook 'eshell-mode-hook
  	    (defun my-eshell-mode-hook ()
  	      (require 'eshell-z))))
#+end_src

*** eshell did-you-mean
#+begin_src emacs-lisp
  (use-package eshell-did-you-mean
    :ensure t
    :after eshell
    :config
    (eshell-did-you-mean-setup))
#+end_src

*** Create new eshell
https://www.emacswiki.org/emacs/EshellMultipleEshellBuffers
#+begin_src emacs-lisp
  (defun my/eshell-new()
    "Open a new instance of eshell."
    (interactive)
    (eshell 'N))
#+end_src

* Testing
Here there will be all the configs I'm testing, before committing them to the main config.

** TODO hammy - time intervals
https://github.com/alphapapa/hammy.el
Time intervals, such as pomodoro.

#+begin_src emacs-lisp
  (use-package hammy
    :ensure t
    :config
    (hammy-mode))
#+end_src

Define the classic pomodoro timer:
#+begin_src emacs-lisp
  (hammy-define (propertize "🍅" 'face '(:foreground "tomato"))
    :documentation "The classic pomodoro timer."
    :intervals
    (list
     (interval :name "Work"
               :duration "25 minutes"
               :before (do (announce "Starting work time.")
  			 (notify "Starting work time."))
               :advance (do (announce "Break time!")
                            (notify "Break time!")))
     (interval :name "Break"
               :duration (do (if (and (not (zerop cycles))
                                      (zerop (mod cycles 3)))
  			       ;; If a multiple of three cycles have
  			       ;; elapsed, the fourth work period was
  			       ;; just completed, so take a longer break.
  			       "30 minutes"
                               "5 minutes"))
               :before (do (announce "Starting break time.")
  			 (notify "Starting break time."))
               :advance (do (announce "Break time is over!")
                            (notify "Break time is over!")))))
#+end_src
** TODO markdown mode
#+begin_src emacs-lisp
  (use-package markdown-mode
    :ensure t
    :mode ("README\\.md\\'" . gfm-mode)
    :init (setq markdown-command '("pandoc" "--from=markdown" "--to=html5")))
#+end_src

** TODO casual - opinionated menus for emacs
https://github.com/kickingvegas/casual-suite?tab=readme-ov-file

I want to have a set of menus where I can see the different options and discover commands I didn't know about. See this video for the explanation:
https://toobnix.org/w/5vCCqXFtWJ3EK7W3HKPRUD

#+begin_src emacs-lisp
  (use-package casual
  :ensure t
  :config
  ;;casual agenda
  (require 'casual-agenda) ; optional if using autoloaded menu
  (keymap-set org-agenda-mode-map "C-o" #'casual-agenda-tmenu)
  ;; casual bookmarks
  (require 'casual-bookmarks) ; optional if using autoloaded menu
  (keymap-set bookmark-bmenu-mode-map "C-o" #'casual-bookmarks-tmenu)
  ;; casual dired
  (require 'casual-dired) ; optional if using autoloaded menu
  (keymap-set dired-mode-map "C-o" #'casual-dired-tmenu)
  (keymap-set dired-mode-map "s" #'casual-dired-sort-by-tmenu) ; optional
  (keymap-set dired-mode-map "/" #'casual-dired-search-replace-tmenu) ; optional

  (require 'casual-editkit) ; optional if using autoloaded menu
  (keymap-global-set "C-o" #'casual-editkit-main-tmenu)

  (require 'casual-ibuffer) ; optional if using autoloaded menu
  (keymap-set ibuffer-mode-map "C-o" #'casual-ibuffer-tmenu)
  (keymap-set ibuffer-mode-map "F" #'casual-ibuffer-filter-tmenu)
  (keymap-set ibuffer-mode-map "s" #'casual-ibuffer-sortby-tmenu)

  (require 'casual-info) ; optional if using autoloaded menu
  (keymap-set Info-mode-map "C-o" #'casual-info-tmenu))
#+end_src

** TODO show-font

#+begin_src emacs-lisp
  (use-package show-font
    :ensure t
    :defer t)
#+end_src

* home related load and startup
This will be loaded automatically when at home.

#+begin_src emacs-lisp
  (if my-homeenvironment-p
      (progn
        ;; here comes the actions I want to be done at a home environment
        (org-babel-load-file "~/.emacs.d/emacs-config-personal.org")))
#+end_src

* Work related config load
Load the work related config when needed:
#+begin_src emacs-lisp
  ;; process all elpaca queues before loading work environment
  (if my-workenvironment-p
    (progn
      ;; here comes the actions I want to be done at work environment
      (org-babel-load-file "~/.emacs.d/emacs-config-work.org")))
#+end_src

* my own keymap
I want to have my own dedicated keymap for the functions I use the most.

From https://protesilaos.com/codelog/2024-01-29-emacs-prefix-map/
#+begin_src emacs-lisp
  (message "loading my own keymap")

  ;; all my online functions in a convenient keybinding map
  (defvar-keymap my/key-prefix-online-map
    :doc "Functions related to online activity"
    "e" #'eww
    "f" (when (fboundp #'elfeed)
  	(cons "elfeed" #'my/elfeed))
    "m" (when (fboundp #'mastodon)
  	(cons "mastodon" #'mastodon)))

  ;; all my theme or font related keybindings
  (defvar-keymap my/key-prefix-themes-map
    :doc "Functions related to theme activities"
    "f" #'fontaine-set-preset
    "t" #'consult-theme
    "v" #'visual-fill-column-mode)

  ;; all my buffer related functions
  (defvar-keymap my/key-prefix-buffers-map
    :doc "Functions related to manipulate buffers"
    ;; empty, for now
    "o" #'my/scratch-org-buffer)

  (defvar-keymap my/key-prefix-direct-access-map
    :doc "Functions related to open my frequently used files."
    "c" (cons "personal config"
  	     (lambda ()
  	       (interactive)
  	       (persp-state-load "~/Nextcloud/config/.emacs.d/perspectives/config-persp")))
    "k" (cons "emacs keys"
  	(lambda ()
  	  (interactive)
  	  (find-file "~/Nextcloud/tech/org-keys.org")))
    "t" (cons "tasks file"
  	   (lambda ()
  	     (interactive)
  	     (persp-state-load "~/Nextcloud/config/.emacs.d/perspectives/tareas-persp")))
    "e" (cons "escritura persp"
  	      (lambda ()
  		(interactive)
  		(persp-state-load
  		 (expand-file-name "escritura-persp"
  				   my-persp-save-dir)))))

  ;; general keybindings for my personal keymaps
  (defvar-keymap my/key-prefix-map
    :doc "My personal keymap."
    "b" (cons "buffers" my/key-prefix-buffers-map)
    "c" #'my/centered-mode
    "i" #'tempel-insert
    "o" (cons "online" my/key-prefix-online-map)
    "q" (cons "direct file access" my/key-prefix-direct-access-map)
    "u" #'consult-outline
    "r" #'consult-recent-file
    "t" (cons "themes and fonts" my/key-prefix-themes-map)
    "w" (when (boundp 'my/key-prefix-writing-map)
  	(cons "writing" my/key-prefix-writing-map))) 

  (keymap-set global-map "C-q" my/key-prefix-map)

  (message "finishing loading my keymap")
#+end_src

* Export config :noexport:ignore:
# ############################
# General options
# ############################
#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK")
#+OPTIONS: date:t e:t email:nil f:t inline:t num:t p:nil pri:nil
#+OPTIONS: prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t
#+OPTIONS: toc:2 todo:t |:t

#+EXCLUDE_TAGS: noexport
#+EXPORT_FILE_NAME:

# ######################
# latex related options
# ######################
#+LATEX_CLASS: memoir
#+LATEX_HEADER:
#+LATEX_HEADER_EXTRA:
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:

# ######################
# odt related options
# ######################
#+OPTIONS: tex:t
#+ODT_STYLES_FILE: "~/Nextcloud/escritura/recursos/orgtemplate2odt.ott"
#+DESCRIPTION:
#+KEYWORDS:
#+SUBTITLE:
#+LATEX_HEADER:

# ######################
# HTML related options
# ######################
#+DESCRIPTION:
#+HTML_DOCTYPE: html5

# ######################
# epub related options
# ######################
#+UID:
#+Subject:
#+Description:
#+Publisher:
#+License:
#+EPUBSTYLE:
#+EPUBCOVER:
#+HTML_DOCTYPE: xhtm

# Local Variables:
# ispell-local-dictionary: "en_US"
# end:
