#+title: Org export
#+property: header-args:emacs-lisp :tangle "55-org-export.el"
#+startup: overview

Every org exporter in one place: the headline-ignore setup, HTML/htmlize,
markdown, the LaTeX and memoir classes, beamer, minted, ox-hugo and ox-epub.
The blog-draft capture template that feeds ox-hugo lives with the other
capture templates in =40-org.org=.

Nothing here is deferred: this module loads =ox= itself, and does not rely on
any other module having done so (org-scribe, in =60-writing=, loads later).
Deferring would buy nothing today, because org-scribe loads =ox= at startup
anyway.  If org-scribe is ever dropped, deferral becomes worth it: use
=use-package= forms with =:after ox= / =:defer t= for the packages, plus a single
=(with-eval-after-load 'ox-latex ...)= around the class definitions.

Home only: the work environment has no exporters configured.

* Lexical binding
#+begin_src emacs-lisp
  ;; -*- lexical-binding: t; -*-
#+end_src

* Orgmode export config
All the functions defined for the org mode export

** Ignore exporting some headlines (just the headlines)
This allows headlines to be ignored in the exports. To do so, the ignore tag (=C-c C-c ignore=) has to be in the header to be ignored. *We only ignore the headlines, the content is still shown.*

#+begin_src emacs-lisp
  ;;(load (expand-file-name "vendor/ox-extra/ox-extra.el" my-data-dir))
  (use-package org-contrib
    :ensure t
    :config
    (require 'ox-extra)
    (ox-extras-activate '(ignore-headlines)))
#+end_src

** html export
*** Remove the "validate" link from html exports
#+begin_src emacs-lisp
  ;; don't show the "validate" link on org-html exports
  (setq org-html-validation-link nil)
#+end_src

*** install htmlize
This package is required to create the vanilla html export.

#+begin_src emacs-lisp
  (use-package htmlize
    :ensure t)
#+end_src

** Markdown export
Export to markdown

#+begin_src emacs-lisp
  (require 'ox-md)
#+end_src

** TODO Latex export
All the latex exports in just one place.

Config extracted from the Emacs Writing Studio ebook.
#+begin_src emacs-lisp
  (use-package ox-latex
    :ensure nil
    :demand t
    :custom
    ;; Multiple LaTeX passes for bibliographies
    (org-latex-pdf-process
     '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
       "bibtex %b"
       "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
       "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
    ;; Add smart quotes for latex
    (org-export-with-smart-quotes t)
    ;; Clean temporary files after export
    (org-latex-logfiles-extensions
     (quote ("lof" "lot" "tex~" "aux" "idx" "log" "out"
             "toc" "nav" "snm" "vrb" "dvi" "fdb_latexmk"
             "blg" "brf" "fls" "entoc" "ps" "spl" "bbl"
             "tex" "bcf"))))
#+end_src
*** ews format
Extracted from the Emacs Writing Studio config.

#+begin_src emacs-lisp
  (with-eval-after-load 'ox-latex
    (add-to-list
     'org-latex-classes
     '("ews"
       "\\documentclass[11pt, twoside, hidelinks]{memoir}
      \\setstocksize{9.25in}{7.5in}
      \\settrimmedsize{\\stockheight}{\\stockwidth}{*}
      \\setlrmarginsandblock{2cm}{1cm}{*} 
      \\setulmarginsandblock{1.5cm}{2.25cm}{*}
      \\checkandfixthelayout
      \\setcounter{tocdepth}{0}
      \\OnehalfSpacing
      \\usepackage{ebgaramond}
      \\usepackage[htt]{hyphenat}
      \\chapterstyle{bianchi}
      \\setsecheadstyle{\\normalfont \\raggedright \\textbf}
      \\setsubsecheadstyle{\\normalfont \\raggedright \\textbf}
      \\setsubsubsecheadstyle{\\normalfont\\centering}
      \\renewcommand\\texttt[1]{{\\normalfont\\fontfamily{cmvtt}
        \\selectfont #1}}
      \\usepackage[font={small, it}]{caption}
      \\pagestyle{myheadings}
      \\usepackage{ccicons}
      \\usepackage[authoryear]{natbib}
      \\bibliographystyle{apalike}
      \\usepackage{svg}"
       ("\\chapter{%s}" . "\\chapter*{%s}")
       ("\\section{%s}" . "\\section*{%s}")
       ("\\subsection{%s}" . "\\subsection*{%s}")
       ("\\subsubsection{%s}" . "\\subsubsection*{%s}"))))
#+end_src

*** Consolidated Memoir LaTeX Export Classes
https://www.ctan.org/pkg/memoir
https://mirror.ibcp.fr/pub/CTAN/macros/latex/contrib/memoir/memman.pdf
=memoir= is a class used to create beautiful documents.

The classes defined here are:
- =memoir=
- =memoir_draft=
- =memoir_chapter=
- =memoir_chapter_draft=

This consolidated function creates all memoir variants (draft/final, with parts/chapter-only).

#+begin_src emacs-lisp
  (defvar my/latex-spanish-preamble
    "\\usepackage[utf8]{inputenc}
  \\usepackage[T1]{fontenc}
  \\usepackage[spanish]{babel}
  \\usepackage{graphicx}
  \\usepackage{todonotes}
  \\usepackage[normalem]{ulem}
  \\usepackage{hyperref}
  \\usepackage{parskip}
  \\usepackage{fourier}
  \\newcommand{\\fin}{\\plainbreak*{3}}
  \\newcommand{\\edit}[1]{\\todo[inline]{#1}}
  \\newcommand{\\adendo}[1]{\\todo[size=\\tiny]{#1}}"
    "Shared LaTeX preamble for Spanish memoir/reporting classes.")

  (defun my/add-memoir-class (name &optional draft chapter-only)
    "Add memoir LaTeX class with NAME.
  When DRAFT is non-nil, enable draft mode.
  When CHAPTER-ONLY is non-nil, start with chapters (no parts)."
    (let* ((draft-option (if draft ",draft" ",final"))
           (levels (if chapter-only
                       ;; Chapter-only: no \\part level
                       '(("\\chapter{%s}" . "\\chapter*{%s}")
                         ("\\section{%s}" . "\\section*{%s}")
                         ("\\subsection{%s}" . "\\subsection*{%s}")
                         ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                         ("\\paragraph{%s}" . "\\paragraph*{%s}")
                         ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))
                     ;; Standard: includes \\part level
                     '(("\\part{%s}" . "\\part*{%s}")
                       ("\\chapter{%s}" . "\\chapter*{%s}")
                       ("\\section{%s}" . "\\section*{%s}")
                       ("\\subsection{%s}" . "\\subsection*{%s}")
                       ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                       ("\\paragraph{%s}" . "\\paragraph*{%s}")
                       ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
           (preamble (concat
                      (format "\\documentclass[a4paper,17pt%s,openright,twoside]{memoir}\n"
                              draft-option)
                      my/latex-spanish-preamble
                      "
  \\usepackage{minted}

  %% Chapter style
  \\chapterstyle{dash}

  %% How the page is formatted
  \\pagestyle{Ruled}

  %% change the paragraph spacing
  \\setlength{\\parskip}{0.2\\baselineskip}

                 [NO-DEFAULT-PACKAGES]
                 [NO-PACKAGES]")))
      (add-to-list 'org-latex-classes
                   `(,name ,preamble ,@levels))))

  (with-eval-after-load 'ox-latex
    (my/add-memoir-class "memoir" nil nil)           ; Standard with parts
    (my/add-memoir-class "memoir_draft" t nil)       ; Draft with parts
    (my/add-memoir-class "memoir_chapter" nil t)     ; Final, chapter-only
    (my/add-memoir-class "memoir_chapter_draft" t t)) ; Draft, chapter-only
#+end_src

*** TODO reporting class for org2latex (complete these options)

#+begin_src emacs-lisp
  (with-eval-after-load 'ox-latex
    (add-to-list 'org-latex-classes
                 `("reporting"
                   ,(concat "\\documentclass[a4paper,17pt,openright,twoside]{memoir}\n"
                            my/latex-spanish-preamble
                            "

  %% How the page is formatted
  \\pagestyle{plain}

                 [NO-DEFAULT-PACKAGES]
                 [NO-PACKAGES]")
                   ("\\part{%s}" . "\\part*{%s}")
                   ("\\chapter{%s}" . "\\chapter*{%s}")
                   ("\\section{%s}" . "\\section*{%s}")
                   ("\\subsection{%s}" . "\\subsection*{%s}")
                   ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                   ("\\paragraph{%s}" . "\\paragraph*{%s}")
                   ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+end_src

** orgmode export
We can export a document to org mode

#+begin_src emacs-lisp
  (require 'ox-org)
#+end_src

** Beamer
Export to beamer.
https://orgmode.org/worg/exporters/beamer/tutorial.html

#+begin_src emacs-lisp
  (require 'ox-beamer)
  (setq org-export-allow-bind-keywords t)
  (setq org-latex-src-block-backend 'minted)
#+end_src

** minted
Source blocks in LaTeX export use =minted=.  The babel languages themselves are
set in =40-org=, since running a block does not need the exporters.
#+begin_src emacs-lisp
  (add-to-list 'org-latex-packages-alist '("" "minted"))
#+end_src

* ox-hugo
To create a static page blog with hugo, based on the orgmode format.
https://ox-hugo.scripter.co/

#+begin_src emacs-lisp
  (use-package ox-hugo
    :ensure t   ;Auto-install the package from Melpa
    :after ox)
#+end_src

* TODO epub exporter
#+begin_src emacs-lisp
  (use-package ox-epub
    :ensure t)
#+end_src

* Pandoc exporter
#+begin_src emacs-lisp
  (use-package ox-pandoc
    :ensure t)
#+end_src
