;; -*- lexical-binding: t; -*-

(defun my/writing-focus-mode ()
  "Toggle a distraction-free writing environment.
Uses my/centered-mode for margins, extra line spacing, and hides line numbers."
  (interactive)
  (if (bound-and-true-p my/centered-mode)
      (progn
        (my/centered-mode -1)
        (setq-local line-spacing 0)
        (display-line-numbers-mode 1))
    (progn
      (my/centered-mode 1)
      (setq-local line-spacing 4)
      (display-line-numbers-mode -1))))

(global-set-key (kbd "C-c 5") #'my/writing-focus-mode)

(use-package gt 
  :ensure t
  :config
  (setq gt-langs '(en es))
  ;; Configure the default translator
  (setq gt-default-translator
	(gt-translator
	 ;; Optional: Use a more specific Taker to ensure correct language handling
	 ;; This Taker focuses on the word or selected region, using the global gt-langs
	 :taker (gt-taker :langs gt-langs :text 'word) 
	 ;; Specify the translation engine(s)
	 :engines (gt-bing-engine)
	 ;; Optional: Change the output method for potentially better readability
	 ;; For example, using a dedicated buffer instead of the echo area:
	 ;; :render (gt-buffer-render)
	 ;; Or using a floating window:
	 ;; :render (gt-posframe-pop-render)
	 ;; The default render (gt-render) outputs to the echo area.
	 )))

(use-package tempel
  :ensure t
  :after org
  ;; Require trigger prefix before template name when completing.
  :custom
  (tempel-trigger-prefix "<")

  :init
  ;; Setup completion at point
  (defun tempel-setup-capf ()
    ;; Add the Tempel Capf to `completion-at-point-functions'.
    ;; `tempel-expand' only triggers on exact matches. Alternatively use
    ;; `tempel-complete' if you want to see all matches, but then you
    ;; should also configure `tempel-trigger-prefix', such that Tempel
    ;; does not trigger too often when you don't expect it. NOTE: We add
    ;; `tempel-expand' *before* the main programming mode Capf, such
    ;; that it will be tried first.
    (setq-local completion-at-point-functions
		(cons #'tempel-expand
                      completion-at-point-functions)))

  (add-hook 'conf-mode-hook 'tempel-setup-capf)
  (add-hook 'prog-mode-hook 'tempel-setup-capf)
  (add-hook 'text-mode-hook 'tempel-setup-capf)
  :bind
  ;;("C-c d i" . tempel-insert)
  :config
  (setq tempel-path "~/.emacs.d/templates"))

(use-package treemacs
:ensure t
:config

;; switch to the project for the current buffer.
;;(treemacs-project-follow-mode)

;; display the current project, and *only* the current project.
;; this should be on the config when enabling the writing mode, not global:
;; (treemacs-add-and-display-current-project-exclusively)

;; to set a visual guide for indentation
(treemacs-indent-guide-mode)

(treemacs-filewatch-mode t)
(treemacs-fringe-indicator-mode 'always)
:bind
(:map global-map
    ("M-0"       . treemacs-select-window)
    ("C-x t 1"   . treemacs-delete-other-windows)
    ("C-x t t"   . treemacs)
    ("C-x t d"   . treemacs-select-directory)
    ("C-x t B"   . treemacs-bookmark)
    ("C-x t C-t" . treemacs-find-file)
    ("C-x t M-t" . treemacs-find-tag)))

(defun org-export-replace-scene-breaks (text backend _info)
  "Replace SCENE-BREAK markers with backend-appropriate scene separators."
  (let ((replacement
         (pcase backend
           ;; Markdown, ASCII, man: visible marker for reliability
           ((or 'ascii 'md 'man)
            "\n***\n\n")
           ;; HTML: visual spacing
           ('html "<br><br><br>\n")
           ;; LaTeX/PDF: vertical space
           ('latex "\\vspace{\\baselineskip}\\vspace{\\baselineskip}\\vspace{\\baselineskip}\n")
           ;; Everything else: 3 blank lines
           (_ "\n\n\n"))))
    (replace-regexp-in-string "SCENE-BREAK" replacement text t t)))

;; `org-export-filter-final-output-functions' is defined in ox, so touching
;; it at startup would force the exporter to load.  Register on ox instead.
(with-eval-after-load 'ox
  (add-to-list 'org-export-filter-final-output-functions
               #'org-export-replace-scene-breaks))

(defvar my-writing-stories-directory "~/Nextcloud/escritura/historias/ejercicios"
  "Directory where org files created by `my-writing--new-file' will be stored.")

(defun my-writing--new-file (title &optional with-prompt)
  "Create and open a new writing file named after TITLE.
The file is stored in `my-writing-stories-directory' with the name format
`%Y%m%d-<title>.org' (spaces in TITLE replaced by underscores) and a standard
org front matter.  When WITH-PROMPT is non-nil, append a writing prompt
generated by the writing_companion script."
  (let* ((date (format-time-string "%Y%m%d"))
         (file-name (concat date "-" (replace-regexp-in-string " " "_" title) ".org"))
         (file-path (expand-file-name file-name my-writing-stories-directory))
         (front-matter (format "#+TITLE: %s\n#+AUTHOR: %s\n#+EMAIL: %s\n#+MACRO: scene-break SCENE-BREAK\n"
                               title user-full-name user-mail-address))
         (prompt (when with-prompt
                   (shell-command-to-string
                    "python  ~/Nextcloud/escritura/software/writing_companion/writing_companion.py -s all prompt"))))
    (with-temp-file file-path
      (insert front-matter)
      (when prompt (insert "\n\n" prompt)))
    (find-file file-path)))

(defun my-writing/create-empty-writing-file (title)
  "Create and open a new empty writing file named after TITLE."
  (interactive "sEnter file name: ")
  (my-writing--new-file title))

(defun my-writing/create-writing-exercise (title)
  "Create and open a new writing file named after TITLE, seeded with a generated prompt."
  (interactive "sEnter file name: ")
  (my-writing--new-file title t))

(defvar my-writing-root
  (expand-file-name "~/Nextcloud/escritura/historias/novela")
  "Root directory holding my writing projects, one subdirectory per project.")

(defvar my/last-writing-project nil
  "Last writing project chosen via `my/start-writing-session'.
Persisted across sessions via `savehist-additional-variables'.")

(defun my-writing--projects ()
  "Return the subdirectories of `my-writing-root' as a list of names."
  (when (file-directory-p my-writing-root)
    (seq-filter
     (lambda (name)
       (and (not (string-prefix-p "." name))
            (file-directory-p (expand-file-name name my-writing-root))))
     (directory-files my-writing-root))))

(defun my/start-writing-session (project)
  "Open a writing PROJECT and enter the writing environment.
Interactively, prompt to pick among the subdirectories of `my-writing-root',
defaulting to the last project used (remembered across sessions).  Press RET on
the empty prompt to reopen that last project."
  (interactive
   (let* ((projects (my-writing--projects))
          ;; surface the last-used project first so it is the primary choice
          (ordered (if (and my/last-writing-project
                            (member my/last-writing-project projects))
                       (cons my/last-writing-project
                             (remove my/last-writing-project projects))
                     projects)))
     (list (completing-read
            (format-prompt "Writing project" my/last-writing-project)
            ordered nil t nil nil my/last-writing-project))))
  (setq my/last-writing-project project)
  (let ((default-directory (file-name-as-directory
                            (expand-file-name project my-writing-root))))
    (call-interactively #'project-find-file))
  (when (fboundp 'org-scribe/writing-env-mode)
    (org-scribe/writing-env-mode 1)))

(defvar-keymap my/key-prefix-writing-map
  :doc "Functions related to writing"
  ;; open a writing session
  "o" #'my/start-writing-session
  ;; writing mode
  "a" #'org-scribe/writing-env-mode
  "f" #'org-scribe/writing-env-mode-focus
  "e" #'org-scribe/editing-mode
  "w" #'org-scribe/ews-org-count-words
  "c" #'org-context-count-words
  ;; writing exercises
  "r" #'my-writing/create-writing-exercise
  "q" #'my-writing/create-empty-writing-file
  "s" #'org-scribe/sinonimo
  ;; hydra keybinding
  "k" #'hydra-org-scribe/body)

(keymap-global-set "<f8> <f8>" #'hydra-org-scribe/body)
;; true one-key entry point for a writing session
(keymap-global-set "<f7>" #'my/start-writing-session)

(use-package org-ql
  :ensure t)

(use-package writeroom-mode
  :ensure t)

(use-package org-context-extended
  :vc (:url "https://codeberg.org/jcastp/org-context-extended"
	    :branch "main"
	    :rev :newest))

(use-package org-tracktable
  :vc (:url "https://codeberg.org/jcastp/org-tracktable"
	    :branch "main"
	    :rev :newest))

(use-package hydra
  :ensure t)

(if (f-directory-p "~/Nextcloud/escritura/software/org-scribe")
    ;; the condition is true
    (progn
      (add-to-list 'load-path "~/Nextcloud/escritura/software/org-scribe")
      (require 'org-scribe)
      (message "org-scribe: local dir loaded"))
  ;; the condition is false
  (progn
    (use-package org-scribe
      :vc (:url "https://codeberg.org/jcastp/org-scribe"
		:branch "development"
		:rev :newest))
    (message "org-scribe: used remote repo")))

;; Enable in org-mode
(add-hook 'org-mode-hook #'org-scribe-mode)

;; Optional: set up keybindings
(org-scribe-setup)

(setq org-scribe-auto-wordcount t)

(if (and my-homeenvironment-p
	 my-clear-directory-is-mounted-p)
    (use-package org-journal
      :ensure t
      :bind
      ("C-c r ñ" . org-journal-new-entry)
      :config
      (setq org-journal-date-prefix "#+TITLE: ")
      (setq org-journal-file-format "%Y-%m-%d.org")
      ;;(setq org-journal-dir "~/Nextcloud/personal/diario/")
      (setq org-journal-dir (expand-file-name "personal/diario" my-clear-directory))
      (setq org-journal-date-format "%A, %d %B %Y")
      (setq org-journal-encrypt-journal nil)))

(my/key-define "i" "insert template" #'tempel-insert)
(my/key-define "w" "writing" my/key-prefix-writing-map)
